# Generated by Django 3.2.4 on 2021-06-30 12:38

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_tile_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='multimedia_obj',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[900, 900], upload_to='img/%y'),
        ),
    ]
